### ISSUE TITLE
cmake policy warning CMP0110

### ISSUE THREAD

**Issue by ckreibich** [zeek/cmake#46]
I've started to see the following in fresh configure runs on the Zeek master, likely triggered [here](https://github.com/zeek/cmake/blob/master/ZeekPluginCommon.cmake). I have cmake 3.22.2.

```
-- Configuring done
CMake Warning (dev) in src/logging/writers/ascii/CMakeLists.txt:
  Policy CMP0110 is not set: add_test() supports arbitrary characters in test
  names.  Run "cmake --help-policy CMP0110" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  The following name given to add_test() is invalid if CMP0110 is not set or
  set to OLD:

    `writers.ascii prefix_basename_with´

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
```

**Comment by timwoj** [comment]
Looks like this policy was added in CMake 3.19.0: https://cmake.org/cmake/help/v3.19/policy/CMP0110.html. That page doesn't exist prior to that version. Apparently it was previously invalid for us to have spaces in test names, but we got away with it by surrounding the test case name with quotes as described in the docs.
