### ISSUE TITLE
zeek_add_plugin: No zeek_plugin_scripts() equivalent?

### ISSUE THREAD

**Issue by awelzel** [zeek/cmake#75]
I was looking at converting the init-plugin script's CMakeLists.txt to the new world order:

https://github.com/zeek/zeek-aux/blob/master/plugin-support/skeleton/CMakeLists.txt

It seems for `zeek_plugin_scripts()` there's no corresponding parameter for `zeek_add_plugin()` - was that on purpose? 

`zeek_plugin_scripts()` was added not too long ago with fb332b85. Maybe I missed some discussion that this isn't wanted anymore, but potentially confuses users converting to the new approach what to do with existing `zeek_plugin_scripts()`.

**Comment by awelzel** [comment]
@Neverlord - tagging you if you had any thoughts. Possibly very related to zeek/zeek#3107 in that we don't seem to honor these files anymore.

**Comment by timwoj** [comment]
Is it possible that this block from ZeekPluginDynamic is supposed to take care of that automatically?

https://github.com/zeek/cmake/blob/1b7be564b08a6071fca7277b285e76d64387facf/ZeekPluginDynamic.cmake#L100-L106

**Comment by Neverlord** [comment]
> Is it possible that this block from ZeekPluginDynamic is supposed to take care of that automatically?

I believe so.
